import type { Config } from "tailwindcss";
import { breakpointsTokens } from "./src/core/theme/tokens/breakpoints";
import { HtmlDataAttribute } from "./src/core/types/enum";
import { creatColorChannel, createTailwinConfg } from "./src/core/utils/theme";

export default {
	darkMode: ["selector", `[${HtmlDataAttribute.ThemeMode}='dark']`],
	content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
	theme: {
		fontFamily: createTailwinConfg("typography.fontFamily"),
		extend: {
			colors: {
				primary: creatColorChannel("colors.palette.primary"),
				success: creatColorChannel("colors.palette.success"),
				warning: creatColorChannel("colors.palette.warning"),
				error: creatColorChannel("colors.palette.error"),
				info: creatColorChannel("colors.palette.info"),
				gray: creatColorChannel("colors.palette.gray"),
				common: creatColorChannel("colors.common"),
				text: creatColorChannel("colors.text"),
				bg: creatColorChannel("colors.background"),
				action: createTailwinConfg("colors.action"),
				background: "var(--background)",
				foreground: "var(--foreground)",
				card: "var(--card)",
				cardForeground: "var(--card-foreground)",
				"card-foreground": "var(--card-foreground)",
				popover: "var(--popover)",
				popoverForeground: "var(--popover-foreground)",
				"popover-foreground": "var(--popover-foreground)",
				primaryForeground: "var(--primary-foreground)",
				"primary-foreground": "var(--primary-foreground)",
				secondary: "var(--secondary)",
				secondaryForeground: "var(--secondary-foreground)",
				"secondary-foreground": "var(--secondary-foreground)",
				muted: "var(--muted)",
				mutedForeground: "var(--muted-foreground)",
				"muted-foreground": "var(--muted-foreground)",
				accent: "var(--accent)",
				accentForeground: "var(--accent-foreground)",
				"accent-foreground": "var(--accent-foreground)",
				destructive: "var(--destructive)",
				"destructive-foreground": "var(--destructive-foreground)",
				border: "var(--border)",
				input: "var(--input)",
				ring: "var(--ring)",
				chart1: "var(--chart-1)",
				chart2: "var(--chart-2)",
				chart3: "var(--chart-3)",
				chart4: "var(--chart-4)",
				chart5: "var(--chart-5)",
				sidebar: "var(--sidebar)",
				sidebarForeground: "var(--sidebar-foreground)",
				"sidebar-foreground": "var(--sidebar-foreground)",
				sidebarPrimary: "var(--sidebar-primary)",
				sidebarPrimaryForeground: "var(--sidebar-primary-foreground)",
				"sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
				sidebarAccent: "var(--sidebar-accent)",
				sidebarAccentForeground: "var(--sidebar-accent-foreground)",
				"sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
				sidebarBorder: "var(--sidebar-border)",
				sidebarRing: "var(--sidebar-ring)",
			},
			opacity: createTailwinConfg("opacity"),
			borderRadius: createTailwinConfg("borderRadius"),
			boxShadow: createTailwinConfg("shadows"),
			spacing: createTailwinConfg("spacing"),
			zIndex: createTailwinConfg("zIndex"),
			screens: breakpointsTokens,
		},
	},
} satisfies Config;
