/**
 * API Response Codes
 */
export const ResponseCodes = {
	// Success codes
	SUCCESS: "SUCCESS",
	CREATED: "CREATED",

	// Authentication codes
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	TOKEN_INVALID: "TOKEN_INVALID",
	UNAUTHORIZED: "UNAUTHORIZED",

	// User codes
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
	DUPLICATE_NIT: "DUPLICATE_NIT",

	// Validation codes
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
	MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

	// Server codes
	INTERNAL_ERROR: "INTERNAL_ERROR",
	SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

	// Resource codes
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",
	FORBIDDEN: "FORBIDDEN",
	DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
} as const;

export type ResponseCode = (typeof ResponseCodes)[keyof typeof ResponseCodes];
